% -------------------------------------------------------------------
%  Generated by MATLAB on 29-Jun-2023 17:34:22
%  MATLAB version: 9.13.0.2080170 (R2022b) Update 1
% -------------------------------------------------------------------
saveVarsMat = load('one.mat');

User_defined_hist_energy = saveVarsMat.User_defined_hist_energy; % <93x35 char> too many elements

clear saveVarsMat;
